export default {
  searchLine: {
    marginTop: "75px",
    display: "flex",
    width: "850px",
    height: "75px",
    borderRadius: "50px",
    border: "3px solid rgba(0, 0, 0, 0.5)",
  },
  searchParamDiv: {
    cursor: "pointer",
    justifySelf: "center",
    margin: "auto",
    display: "table",
  },
  vericalLine: {
    with: "1px",
    height: "75%",
    border: "1px solid rgba(0, 0, 0, 1)",
    marginTop: "auto",
    marginBottom: "auto",
  },
  text: {
    color: "rgba(0, 0, 0, 0.75)",
    fontSize: "20px",
    bold: "true",
  },
  bigIcon: {
    fontSize: "50px",
    color: "white",
    padding: "5px",
  },
  smallIcon: {
    fontSize: "24px",
    borderRadius: "50%",
    paddingLeft: "2px",
    marginLeft: "2px",
  },
  bigAd: {
    marginTop: "100px",
    width: "950px",
    height: "500px",
    borderRadius: "25px",
    border: "3px solid rgba(0, 0, 0, 0.5)",
    display: "flex",
    flexDirection: "row",
  },
  buttonInsideAd: {
    height: "50px",
    width: "250px",
    borderRadius: "25px",
    marginTop: "12px",
    marginInline: "auto",
    display: "table",
  },
  smallAd: {
    width: "300px",
    height: "400px",
    borderRadius: "25px",
    border: "3px solid rgba(0, 0, 0, 0.5)",
    display: "flex",
  },
  smallAdBox: {
    marginTop: "25px",
    width: "950px",
    display: "flex",
  },
};
